PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX ex: <http://example.org/>

#CONSTRUCT { ?x ex:shotWithActor ?actor1, ?actor2 }
#DESCRIBE ?y
#DESCRIBE <http://example.org/movie/m2046>
SELECT *
WHERE {
    #-- Test with a term map whose object is an rdf:Seq
    ?x ex:directed ?y .
    ?y ex:starringList ?z .
    ?z a rdf:Seq .
    ?z rdf:_1 ?actor1 .
    # optional { ?z rdf:_2 ?actor2 . }

    #-- Test of rewriting with an iterator
    #?y ex:starringIter ?z .
    
	#<http://example.org/dir/Wong%20Kar-wai> ex:directed ?x .
	
    #?x ex:directed <http://example.org/movie/Manh> .
}
