prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix skosxl: <http://www.w3.org/2008/05/skos-xl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix dct: <http://purl.org/dc/elements/1.1/>

prefix txn: <http://lod.taxonconcept.org/ontology/txn.owl#>
prefix gn: <http://www.geonames.org/ontology#>
prefix nt: <http://purl.obolibrary.org/obo/ncbitaxon#>
prefix dwc: <http://rs.tdwg.org/dwc/terms/>

prefix taxref: <http://inpn.mnhn.fr/taxref/8.0/>
prefix taxrefrk: <http://inpn.mnhn.fr/taxref/taxrank#>
prefix taxrefhab: <http://inpn.mnhn.fr/taxref/habitat#>
prefix taxrefbgs: <http://inpn.mnhn.fr/taxref/bioGeoStatus#>
prefix taxrefprop: <http://inpn.mnhn.fr/taxref/properties/>

#DESCRIBE <http://inpn.mnhn.fr/taxref/label/60585>

SELECT *
WHERE {
    #<http://inpn.mnhn.fr/taxref/8.0/taxon/60585> ?p ?x .
    
    #<http://inpn.mnhn.fr/taxref/8.0/taxon/60585> skos:broader ?u .

    #?y skos:broader ?u .

    #<http://inpn.mnhn.fr/taxref/8.0/taxon/60585> skosxl:prefLabel ?p .
    #OPTIONAL { <http://inpn.mnhn.fr/taxref/8.0/taxon/60585> skosxl:altLabel ?a . }

	## Very big inner join but with propagation of conditions
    #?t skosxl:prefLabel <http://inpn.mnhn.fr/taxref/label/60585> .
    #?t skosxl:altLabel ?a .
 	#?t skosxl:altLabel ?b . 
    #FILTER (?a != ?b)
    
	## Big inner join: no self-join elimination nor condition propagation
    #?t skosxl:altLabel <http://inpn.mnhn.fr/taxref/label/60587> .
 	#?t skosxl:altLabel ?b . 
    #FILTER (?b != <http://inpn.mnhn.fr/taxref/label/60587>)

	## Optional join
    #?t skosxl:altLabel <http://inpn.mnhn.fr/taxref/label/60587> .
    #OPTIONAL { 
    #  ?t skosxl:altLabel ?b .
    #  FILTER (?b != <http://inpn.mnhn.fr/taxref/label/60587>)
    #}
    
	# Big optional Join - no optimization possible
    #?t skosxl:altLabel ?a .
    #OPTIONAL { ?t skosxl:altLabel ?b . FILTER (?a != ?b)
    #}

	## Self-Join and Self-Union elimination using unique reference
    ?t skosxl:prefLabel ?p .
    ?t taxrefprop:bioGeoStatusIn ?bgs . 
    ?bgs dct:spatial <http://sws.geonames.org/3424932/> . # Saint-Pierre-Et-Miquelon
    { ?bgs dwc:occurrenceStatus taxrefbgs:C . } # cryptogenic
    UNION
    { ?bgs dwc:occurrenceStatus taxrefbgs:D . } # also P, Q, A and I
} LIMIT 10
