prefix skos: <http://www.w3.org/2004/02/skos/core#>
prefix skosxl: <http://www.w3.org/2008/05/skos-xl#>
prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix owl: <http://www.w3.org/2002/07/owl#>
prefix dct: <http://purl.org/dc/elements/1.1/>

prefix txn: <http://lod.taxonconcept.org/ontology/txn.owl#>
prefix gn: <http://www.geonames.org/ontology#>
prefix nt: <http://purl.obolibrary.org/obo/ncbitaxon#>
prefix dwc: <http://rs.tdwg.org/dwc/terms/>

prefix taxref: <http://inpn.mnhn.fr/taxref/8.0/>
prefix taxrefrk: <http://inpn.mnhn.fr/taxref/taxrank#>
prefix taxrefhab: <http://inpn.mnhn.fr/taxref/habitat#>
prefix taxrefbgs: <http://inpn.mnhn.fr/taxref/bioGeoStatus#>
prefix taxrefprop: <http://inpn.mnhn.fr/taxref/properties/>

SELECT ?p ?a
WHERE {
    # <http://inpn.mnhn.fr/taxref/8.0/taxon/60585> ?p ?x .
    # <http://inpn.mnhn.fr/taxref/8.0/taxon/60585> skos:broader ?u .

    <http://inpn.mnhn.fr/taxref/8.0/taxon/60585> skosxl:prefLabel ?p .
    OPTIONAL { <http://inpn.mnhn.fr/taxref/8.0/taxon/60585> skosxl:altLabel ?a . }
    
    # ?t taxrefprop:bioGeoStatusIn ?bgs .
    # ?bgs 
    #     dct:spatial <http://sws.geonames.org/3424932/> ; # Saint-Pierre-Et-Miquelon
    #     dwc:occurrenceStatus taxrefbgs:C . # Cryptogène
}
