prefix xrr: <http://i3s.unice.fr/xr2rml#>
prefix rr:  <http://www.w3.org/ns/r2rml#>
prefix rml: <http://semweb.mmlab.be/ns/rml#>
prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix ex: <http://ex.org/bios/>
prefix xsd: <http://www.w3.org/2001/XMLSchema#>

prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>
prefix ex:  <http://ex.org/awards/>
prefix : <http://awards.org/>

SELECT *
WHERE {

#?p a :Person .
#?p :hasFirstName ?fn .
#?p :hasOccupation ?o .
#?p :hasReceived ?rc .
?p :diedOnDay ?dd .

#?f a :Female .

#?m a :Male .

#?a a :Award .
#
#?a :receivedIn ?r .

#?a :hasTitle ?t .
}

LIMIT 100
